## Pandas

In [2]:
import pandas

# Reading csv
dataframe = pandas.read_csv("cancer.csv", header=1)

# Converting dataframe to list
dataframe.values.tolist()[:2]

[['M',
  20.57,
  17.77,
  132.9,
  1326.0,
  0.08474,
  0.07864,
  0.0869,
  0.07017,
  0.1812,
  0.05667,
  0.5435,
  0.7339,
  3.398,
  74.08,
  0.005225,
  0.01308,
  0.0186,
  0.0134,
  0.01389,
  0.003532,
  24.99,
  23.41,
  158.8,
  1956.0,
  0.1238,
  0.1866,
  0.2416,
  0.186,
  0.275,
  0.08902],
 ['M',
  19.69,
  21.25,
  130.0,
  1203.0,
  0.1096,
  0.1599,
  0.1974,
  0.1279,
  0.2069,
  0.05999,
  0.7456,
  0.7869,
  4.585,
  94.03,
  0.00615,
  0.04006,
  0.03832,
  0.02058,
  0.0225,
  0.004571,
  23.57,
  25.53,
  152.5,
  1709.0,
  0.1444,
  0.4245,
  0.4504,
  0.243,
  0.3613,
  0.08758]]

## NumPy

### Создание массивов

In [3]:
import numpy as np

# Converting from and to list
vector = [1, 2, 3]
np_vector = np.array(vector)
vector = np_vector.tolist()
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
matrix = np_matrix.tolist()

In [6]:
# Primitives
ones = np.ones((4, 3, 2))
zeros = np.zeros((2, 3, 4))
np_range = np.arange(1, 6)
np_range = np.arange(1, 6, 0.5)
np_linspace = np.linspace(0, 1, 4)
eye = np.eye(4)

In [8]:
# Random
normal_distribution = np.random.randn(2, 3)
uniform_distribution = np.random.random((2, 3))
integers = np.random.randint(1, 3, (2, 3))

### Индексирование

In [9]:
# Slicing
normal_distribution = np.random.randn(6, 8)

normal_distribution[1, 1]
normal_distribution[:, 1] 
normal_distribution[::-1, 1]
normal_distribution[::2, 1]
normal_distribution[1, :]
normal_distribution[1]

# Берем значения по маске
normal_distribution[(normal_distribution > 0)] # 1d!!!
normal_distribution[np.random.randn(6) > 0] # 2d!!!
normal_distribution[:, np.random.randn(8) > 0] # 2d!!!

# Берем определенные индексы
ids = np.arange(0, 6, 2)
normal_distribution[ids]

array([[ 0.86258656, -0.36609   ,  0.2749017 ,  0.07296435,  0.32863056,
         0.40921108, -0.73621495, -0.91401188],
       [-2.01911706,  0.57456626,  1.50530694,  0.81431302,  0.50309518,
         0.21339445, -1.76247616,  0.08224552],
       [-1.80805482, -0.96329104, -0.45624165,  0.89090701,  0.99692742,
         0.14698561,  0.63862243, -1.65135414]])

In [11]:
# Operations with slices
normal_distribution = np.random.randn(6, 4)
print(normal_distribution)
normal_distribution[:, 1] = 10
print(normal_distribution)

[[ 0.48498972  0.65106238  0.90908295  0.80823376]
 [-1.89011131 -1.83754457 -0.62690791  1.04373145]
 [ 0.76220259 -0.928599   -0.50655543 -0.70256135]
 [ 0.25839875 -0.91344491 -0.59420672 -0.66240846]
 [-1.80725286  0.743495    0.53939028 -1.16715014]
 [ 0.7485508   1.16901376 -1.44253041 -0.15171995]]
[[ 0.48498972 10.          0.90908295  0.80823376]
 [-1.89011131 10.         -0.62690791  1.04373145]
 [ 0.76220259 10.         -0.50655543 -0.70256135]
 [ 0.25839875 10.         -0.59420672 -0.66240846]
 [-1.80725286 10.          0.53939028 -1.16715014]
 [ 0.7485508  10.         -1.44253041 -0.15171995]]


### Математические операции

In [14]:
# Среднее
a = np.random.randn(8, 8)
print(a)
print(np.mean(a))
print(a.mean())
print(a.mean(-1))

[[ 0.75597823  0.32324129 -1.57650476 -0.75869927  0.70975841  0.68992911
  -0.24219349  0.62166549]
 [ 0.74301889 -0.07157463 -0.8107271  -1.59821089  0.96190241  1.5479166
   0.93017035  1.54053698]
 [ 1.17150196  1.26802302 -0.1199408  -1.01606236  1.69211823  0.47820871
  -0.9962631  -0.54002643]
 [-0.11915483  1.33441325 -1.24227772  0.2888722   1.41818512 -1.80615749
  -0.91667907  1.63782603]
 [ 0.03023767  0.82601084  0.85720944 -0.97822882 -0.26736488 -0.79160508
   0.53918714  0.15268024]
 [-1.18701904 -0.74913586  0.84102243  1.56725725  0.04161783 -1.42533324
   2.69282727  2.65985914]
 [ 1.42822809 -1.25959721  0.85991529  0.5450966   0.20307518  0.17923068
  -0.14474574 -0.32011474]
 [ 0.56826254 -0.54545099 -1.25594933  1.2231299  -0.10838525 -0.98787196
   2.00673145 -0.62810903]]
0.20111659595930798
0.20111659595930798
[0.06539687 0.40537908 0.2421949  0.07437844 0.04601582 0.55513697
 0.18638602 0.03404467]


In [13]:
# Максимум
a = np.random.randn(8, 8)
print(np.max(a))
print(a.max())
print(a.max(-1))

2.1837242142635187
2.1837242142635187
[1.21612034 2.18372421 1.57085159 0.63053767 1.67445535 1.2516482
 1.69809636 0.93982367]


In [15]:
# Argmax
a = np.random.randn(8, 8)
print(a)
print(np.argmax(a)) # Position in flattened array
print(a.argmax(-1))

[[ 0.67327078  0.07676248 -1.52652191 -0.21695247  0.53968802  1.29578214
  -0.3582262  -0.65499334]
 [ 0.23604021 -0.30046026 -0.79156066  0.71378757 -0.98243946 -0.47173837
  -1.6608173  -0.75005779]
 [-0.83634907 -0.07416683  1.18235831  1.050711    1.99740948  0.35928339
   0.30815851  0.49455951]
 [-1.03849917 -1.28353223  0.16193655  0.15290383 -0.49004739  0.70900406
   0.73276702  1.03787902]
 [ 1.75376917 -1.11301346  0.78663219  0.49751036  0.37673504 -1.51209175
   0.49348298  2.54394084]
 [-0.9708127   0.15320955 -1.15751084 -0.2746352  -0.92805959 -0.79156126
   0.53448318 -0.28961901]
 [ 0.75281035  0.4308417  -1.2898335   0.60402079  0.7090975   0.20455149
   0.44837969  0.27122491]
 [ 0.45649688 -0.11172882 -0.89300498  0.04007866 -0.44380759  1.65285456
  -1.77486702 -1.00614015]]
39
[5 3 4 7 7 6 0 5]


In [16]:
# Get unique elements
np.unique(np.random.randint(1, 100, 1000), return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([12,  8,  5,  9,  5, 12, 10,  6, 12, 14, 12,  7,  5,  4, 13, 12, 13,
         7, 11,  9,  7,  9,  9,  9, 15,  8, 13,  9, 15,  9, 13,  8, 11,  9,
         9, 11, 11,  5,  5, 15, 13, 11, 11, 16,  3, 10,  9,  8, 11,  9,  7,
        12,  6, 16, 11, 10,  9,  6, 16, 10,  7, 12, 10, 20, 12, 10, 10, 13,
         8,  6, 15, 16, 14,  5,  4, 11,  6, 11,  8, 14, 10, 13, 12,  8,  7,
        10, 13, 13, 12,  8, 13, 12, 11, 10,  8,  5, 11,  8, 14],
       dtype=int64))

In [23]:
np_vector = np.random.randn(16)
np_matrix = np.random.randn(16, 16)

# Elementvise operations
np_vector * np_vector
np_vector - np_vector
np_vector + np_vector
np_vector / np_vector
np_matrix * np_vector
np_matrix - np_vector
np_matrix + np_vector
np_matrix / np_vector

# Tensor operations
np_vector.dot(np_vector) # Production
np_matrix.T # Transpose

array([[-8.64687274e-02, -1.92875426e-01, -3.86599268e-01,
         1.68564827e+00, -2.35416180e+00,  9.55447599e-01,
        -1.01890307e+00,  4.93631755e-01,  4.12445632e-01,
        -6.79618781e-01, -5.58640364e-01, -3.07014056e-01,
         5.19498547e-01, -1.63105506e-01,  3.09015701e-01,
        -1.64425002e+00],
       [ 2.18992800e+00, -8.39579947e-02, -8.04221731e-01,
        -1.19057935e+00, -1.76843865e+00,  1.54203141e+00,
         6.75591005e-01, -5.53028532e-01, -4.65890895e-01,
         3.00397014e-01, -7.77505958e-01, -1.72022665e-01,
         8.45459353e-02, -5.97714456e-01,  2.91086192e-02,
        -1.98910723e+00],
       [-1.04024935e+00,  1.05660984e-01,  8.45841391e-01,
        -1.55220539e-01,  1.22865939e-01,  5.26856540e-01,
         2.11580816e-01,  1.62509295e+00, -3.80954162e-01,
        -5.41665506e-01,  1.00604167e+00, -1.53048421e+00,
         4.31730729e-01,  3.46440116e-01, -4.60389802e-01,
         5.80883645e-01],
       [ 2.22092876e-02, -7.90753474e

In [25]:
a = np.random.randn(8, 8)
print(np.linalg.norm(a))
print(np.linalg.norm(a, axis=-1))

8.290253869114443
[2.62355552 2.54820056 3.48207316 2.83670315 3.56360443 2.79102868
 1.96596203 3.29030348]


### Изменение размерности

In [17]:
# Shape
a = np.linspace(0, 1, 12)
print(a)
a = a.reshape((2, 6))
print(a)
a = a.reshape((-1, 3))
print(a)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545]
 [0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]]
[[0.         0.09090909 0.18181818]
 [0.27272727 0.36363636 0.45454545]
 [0.54545455 0.63636364 0.72727273]
 [0.81818182 0.90909091 1.        ]]


In [18]:
a = np.random.randn(4, 4)
b = np.random.randn(4, 4, 4)
a = np.expand_dims(a, 1)
a = np.broadcast_to(a, b.shape)
print(a)

[[[ 0.33994082  0.99703207 -1.50486959  1.22337382]
  [ 0.33994082  0.99703207 -1.50486959  1.22337382]
  [ 0.33994082  0.99703207 -1.50486959  1.22337382]
  [ 0.33994082  0.99703207 -1.50486959  1.22337382]]

 [[ 1.02848396  0.82195153 -0.44643992  0.77079486]
  [ 1.02848396  0.82195153 -0.44643992  0.77079486]
  [ 1.02848396  0.82195153 -0.44643992  0.77079486]
  [ 1.02848396  0.82195153 -0.44643992  0.77079486]]

 [[ 0.72568159 -1.0635441  -0.13352069  1.26546859]
  [ 0.72568159 -1.0635441  -0.13352069  1.26546859]
  [ 0.72568159 -1.0635441  -0.13352069  1.26546859]
  [ 0.72568159 -1.0635441  -0.13352069  1.26546859]]

 [[ 1.00335748 -0.3863238   0.15893258 -0.84772002]
  [ 1.00335748 -0.3863238   0.15893258 -0.84772002]
  [ 1.00335748 -0.3863238   0.15893258 -0.84772002]
  [ 1.00335748 -0.3863238   0.15893258 -0.84772002]]]
